#!/usr/bin/env node
// Root-cause clustering + triage of the findings graph (answers "how few changes close most findings?").
// Pure analysis — no agents. Groups findings by theme + title-signature overlap (union-find on shared
// distinctive keywords), flags cross-target SWEEP groups (one fix pattern repeated across services), and
// triages each finding into a cost band (LIGHT / FULL / SWEEP / QUEUE). Writes reports/ROOT-CAUSE-TRIAGE.md.
//   node _bmad-output/ai-factory/_workflow/cluster.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve as presolve } from 'node:path';
import { fileURLToPath } from 'node:url';
// Signature + similarity rule extracted to lib/similarity.mjs (2026-07-04) so this triage report,
// `driver.mjs suggest` (similar-batch planning), and `driver.mjs group` (batch-pattern stamping)
// can never drift apart on what "same pattern" means.
import { sig, similarSigs } from './lib/similarity.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = presolve(HERE, '..'); // _bmad-output/ai-factory
const graph = JSON.parse(readFileSync(join(ROOT, 'state', 'findings-graph.json'), 'utf8'));
const items = graph.items || [];

// ---- union-find clustering within a theme by keyword overlap -----------------------------------------
const parent = items.map((_, i) => i);
function find(i) { while (parent[i] !== i) { parent[i] = parent[parent[i]]; i = parent[i]; } return i; }
function union(a, b) { parent[find(a)] = find(b); }

const byTheme = {};
items.forEach((it, i) => { (byTheme[it.theme || '?'] ||= []).push(i); });
const sigs = items.map(sig);

// Within each theme, union findings that share a strong keyword overlap (same root-cause pattern).
for (const idxs of Object.values(byTheme)) {
  for (let a = 0; a < idxs.length; a++) {
    for (let b = a + 1; b < idxs.length; b++) {
      if (similarSigs(sigs[idxs[a]], sigs[idxs[b]])) union(idxs[a], idxs[b]);
    }
  }
}

const clusters = {};
items.forEach((_, i) => { (clusters[find(i)] ||= []).push(i); });

// ---- triage band -------------------------------------------------------------------------------------
const FULL_THEMES = new Set(['security-multitenancy', 'money-correctness', 'idempotency-dataflow']);
function band(it, clusterTargets) {
  if (it.fixType === 'owner-decision' || it.fixType === 'scope-stop' || it.autonomyTier === 'blocked') return 'QUEUE';
  if (clusterTargets >= 3) return 'SWEEP'; // same pattern across >=3 targets — one sweep closes them
  if (it.severity === 'CRITICAL' && FULL_THEMES.has(it.theme)) return 'FULL';
  if (it.theme === 'doc-drift' || it.fixType === 'mechanical') return 'LIGHT';
  if (FULL_THEMES.has(it.theme)) return 'FULL';
  return 'LIGHT';
}

// ---- assemble cluster records ------------------------------------------------------------------------
const recs = Object.values(clusters).map((idxs) => {
  const members = idxs.map((i) => items[i]);
  const targets = [...new Set(members.map((m) => m.target))];
  // cluster label = most common distinctive keywords across members
  const kwCount = {};
  for (const i of idxs) for (const w of sigs[i]) kwCount[w] = (kwCount[w] || 0) + 1;
  const label = Object.entries(kwCount).sort((a, b) => b[1] - a[1]).slice(0, 4).map(([w]) => w).join(' / ') || '(misc)';
  const theme = members[0].theme;
  const sev = { CRITICAL: 0, HIGH: 0, MEDIUM: 0 };
  for (const m of members) sev[m.severity] = (sev[m.severity] || 0) + 1;
  return { size: members.length, targets: targets.length, theme, label, sev, ids: members.map((m) => m.id) };
}).sort((a, b) => b.size - a.size);

// per-finding band tally
const bandCount = { SWEEP: 0, LIGHT: 0, FULL: 0, QUEUE: 0 };
const clusterTargetsById = {};
for (const r of recs) for (const id of r.ids) clusterTargetsById[id] = r.targets;
for (const it of items) bandCount[band(it, clusterTargetsById[it.id] || 1)]++;

// cost model (rough, from the live runs): FULL ~2.0M tok, LIGHT ~0.5M, SWEEP ~2.0M for the WHOLE group
const COST = { FULL: 2.0, LIGHT: 0.5, SWEEP: 2.0, QUEUE: 0 };
const sweepGroups = recs.filter((r) => r.targets >= 3);
const itemByItemTokens = items.reduce((a, it) => a + (band(it, clusterTargetsById[it.id] || 1) === 'QUEUE' ? 0 : (FULL_THEMES.has(it.theme) || it.severity === 'CRITICAL' ? 2.0 : 0.5)), 0);
const sweepTokens = bandCount.SWEEP > 0 ? sweepGroups.length * COST.SWEEP : 0;
const nonSweepTokens = bandCount.LIGHT * COST.LIGHT + bandCount.FULL * COST.FULL;
const optimizedTokens = sweepTokens + nonSweepTokens;

// ---- report ------------------------------------------------------------------------------------------
const L = [];
L.push('# Root-cause clustering + triage — the 617 findings');
L.push('');
L.push(`_Generated by cluster.mjs · ${items.length} findings · ${recs.length} root-cause clusters_`);
L.push('');
L.push('## The headline');
L.push('');
L.push(`The ${items.length} findings collapse into **${recs.length} root-cause clusters**. **${sweepGroups.length} of them are cross-service SWEEPS** `
  + `(the same fix pattern repeated across ≥3 services) covering **${sweepGroups.reduce((a, r) => a + r.size, 0)} findings** — one sweep change closes the whole group.`);
L.push('');
L.push('| Triage band | Findings | What it means | Est. tokens |');
L.push('|---|---|---|---|');
L.push(`| **SWEEP** | ${bandCount.SWEEP} | one root-cause change closes ≥3 services' worth | ~${(sweepTokens).toFixed(1)}M total (${sweepGroups.length} sweeps) |`);
L.push(`| **LIGHT** | ${bandCount.LIGHT} | doc/mechanical — cheap lean band (no opus panel) | ~${(bandCount.LIGHT * COST.LIGHT).toFixed(1)}M |`);
L.push(`| **FULL** | ${bandCount.FULL} | CRITICAL security/money/concurrency — full rigorous band | ~${(bandCount.FULL * COST.FULL).toFixed(1)}M |`);
L.push(`| **QUEUE** | ${bandCount.QUEUE} | owner-decision / scope-stop — human ruling | 0 |`);
L.push('');
L.push(`**Brute-force item-by-item (today): ~${(itemByItemTokens).toFixed(0)}M tokens.** `
  + `**Sweep + triaged: ~${optimizedTokens.toFixed(0)}M tokens** — a ~${Math.round((1 - optimizedTokens / itemByItemTokens) * 100)}% reduction, before counting that LIGHT items run ~4× cheaper.`);
L.push('');
L.push('## Top root-cause clusters (the sweep targets)');
L.push('');
L.push('| # | Pattern (keywords) | Theme | Findings | Services | Sev (C/H/M) | Band |');
L.push('|---|---|---|---|---|---|---|');
recs.slice(0, 30).forEach((r, i) => {
  const b = r.targets >= 3 ? 'SWEEP' : (FULL_THEMES.has(r.theme) ? 'FULL' : 'LIGHT');
  L.push(`| ${i + 1} | ${r.label} | ${r.theme} | ${r.size} | ${r.targets} | ${r.sev.CRITICAL}/${r.sev.HIGH}/${r.sev.MEDIUM} | ${b} |`);
});
L.push('');
L.push('## How to act on this');
L.push('');
L.push('1. **Run the SWEEPs first.** Each closes many findings for ~one fix\'s cost. Biggest leverage.');
L.push('2. **LIGHT band the long tail** — doc-drift + mechanical at ~0.5M tok, no opus review panel.');
L.push('3. **FULL band only the CRITICAL security/money/concurrency** — where rigor pays.');
L.push('4. **QUEUE** the owner-decisions — never spend agents discovering a human is required.');
L.push('');
const out = join(ROOT, 'reports', 'ROOT-CAUSE-TRIAGE.md');
writeFileSync(out, L.join('\n'));
console.log(`clusters: ${recs.length} · sweeps(>=3 svc): ${sweepGroups.length} covering ${sweepGroups.reduce((a, r) => a + r.size, 0)} findings`);
console.log(`bands: SWEEP ${bandCount.SWEEP} · LIGHT ${bandCount.LIGHT} · FULL ${bandCount.FULL} · QUEUE ${bandCount.QUEUE}`);
console.log(`tokens: brute-force ~${itemByItemTokens.toFixed(0)}M -> sweep+triaged ~${optimizedTokens.toFixed(0)}M`);
console.log('top clusters:');
recs.slice(0, 12).forEach((r, i) => console.log(`  ${i + 1}. [${r.size} findings / ${r.targets} svc] ${r.theme}: ${r.label}`));
console.log(`-> ${out}`);

// --emit-pattern "<kw>" [--slug s]: emit a CROSS-CLUSTER sweep of EVERY finding whose title contains <kw>
// (the cleanest sweep primitive — a single homogeneous pattern regardless of which keyword cluster it fell in).
const epArg = process.argv.indexOf('--emit-pattern');
if (epArg >= 0) {
  const kw = String(process.argv[epArg + 1] || '').toLowerCase();
  const slugArg = process.argv.indexOf('--slug');
  const slug = slugArg >= 0 ? process.argv[slugArg + 1] : kw.replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  const match = items.filter((it) => (it.title || '').toLowerCase().includes(kw));
  if (!match.length) { console.log(`no findings match --emit-pattern "${kw}"`); process.exit(1); }
  const tgts = [...new Set(match.map((m) => m.target))];
  const spec = {
    index: slug, label: kw, theme: match[0].theme, band: 'SWEEP', size: match.length, targets: tgts.length,
    sites: match.map((it) => ({ findingId: it.id, target: it.target, files: it.files || [], title: it.title, source: it.source, severity: it.severity })),
  };
  const sdir = join(ROOT, 'state', 'sweeps'); mkdirSync(sdir, { recursive: true });
  const sp = join(sdir, 'sweep-' + slug + '.json'); writeFileSync(sp, JSON.stringify(spec, null, 2));
  console.log(`emitted pattern-sweep "${kw}" (${match.length} findings / ${tgts.length} services) -> ${sp}  [id: ${slug}]`);
  process.exit(0);
}

// --emit <N>: write root-cause cluster N as a SWEEP spec (pattern + sites) for `driver sweep` / runSweep.
const emitArg = process.argv.indexOf('--emit');
if (emitArg >= 0) {
  const n = parseInt(process.argv[emitArg + 1], 10) || 0;
  const r = recs[n];
  if (!r) { console.log('no cluster at index', n); process.exit(1); }
  const byId = Object.fromEntries(items.map((x) => [x.id, x]));
  // --pattern <kw>: tighten the (coarse) theme cluster to a HOMOGENEOUS sub-cluster (sites whose title
  // contains <kw>) — a clean sweep needs ONE pattern, and the keyword clusters mix findings. Strongly
  // recommended before a real sweep (e.g. --emit 0 --pattern PodDisruptionBudget).
  const patArg = process.argv.indexOf('--pattern');
  const pat = patArg >= 0 ? String(process.argv[patArg + 1] || '').toLowerCase() : null;
  const ids = pat ? r.ids.filter((id) => (byId[id].title || '').toLowerCase().includes(pat)) : r.ids;
  if (!ids.length) { console.log(`no sites in cluster ${n} match --pattern "${pat}"`); process.exit(1); }
  const sweepTargets = [...new Set(ids.map((id) => byId[id].target))];
  const spec = {
    index: n, label: pat ? `${r.label} [${pat}]` : r.label, theme: r.theme, band: 'SWEEP', size: ids.length, targets: sweepTargets.length,
    sites: ids.map((id) => { const it = byId[id]; return { findingId: id, target: it.target, files: it.files || [], title: it.title, source: it.source, severity: it.severity }; }),
  };
  const sdir = join(ROOT, 'state', 'sweeps'); mkdirSync(sdir, { recursive: true });
  const sp = join(sdir, 'sweep-' + n + '.json'); writeFileSync(sp, JSON.stringify(spec, null, 2));
  console.log(`emitted sweep ${n} (${ids.length} sites / ${sweepTargets.length} svc · ${r.theme}: ${spec.label}) -> ${sp}`);
}
