import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, statSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { nativeCheckpointRequest, nativeCheckpointRelay } from './native-checkpoint.mjs';
import { nativeRequestJson, nativeRequestSha256 } from './native-evidence-request.mjs';
import { persistNativeCheckpoint } from './native-persistence.mjs';
import { artifactToolDecision, assertArtifactTree, instructionBearingPath, exactArtifactPath } from './native-artifact-guard.mjs';
import { stageNativeContext, hydrateNativeContext } from './native-context.mjs';
import { nativeIntegrationReuseDecision } from './native-integration-reuse.mjs';

const root = mkdtempSync(join(tmpdir(), 'native-artifact-'));
try {
  const dir = join(root, 'item'); mkdirSync(dir);
  const payload = { id: 'item', runId: 'run', claimId: 'claim', attemptNumber: 1, toState: 'IN_PROGRESS', progressStage: 'post-test' };
  const request = nativeCheckpointRequest(dir, 'progress.json', payload);
  const digest = nativeRequestSha256(nativeRequestJson(request));
  const input = join(dir, 'checkpoint-input-' + digest + '.json');
  writeFileSync(input, JSON.stringify(payload));
  assert.deepEqual(persistNativeCheckpoint(dir, input, digest), { written: true });
  const output = join(dir, 'progress.json'), mtime = statSync(output).mtimeMs;
  assert.deepEqual(JSON.parse(readFileSync(output, 'utf8')), payload);
  persistNativeCheckpoint(dir, input, digest);
  assert.equal(statSync(output).mtimeMs, mtime, 'same bytes skip atomic replacement');
  writeFileSync(input, JSON.stringify({ ...payload, toState: 'CLOSED' }));
  assert.throws(() => persistNativeCheckpoint(dir, input, digest), /digest mismatch/);
  assert.equal(statSync(output).mtimeMs, mtime);
  writeFileSync(input, JSON.stringify(payload));
  const persistCli = fileURLToPath(new URL('../native-persist.mjs', import.meta.url));
  const persisted = spawnSync(process.execPath, [persistCli, dir, input, '--expected-request', digest], { encoding: 'utf8' });
  assert.equal(persisted.status, 0, persisted.stderr);
  assert.deepEqual(JSON.parse(persisted.stdout), { written: true });
  assert.equal(spawnSync(process.execPath, [persistCli, dir, input], { encoding: 'utf8' }).status, 1);
  assert.throws(() => persistNativeCheckpoint(dir, join(root, 'outside.json'), digest), /path mismatch/);
  for (const state of ['CLAIMED', 'GREEN', null]) {
    const p = { ...payload, toState: state }, d = nativeRequestSha256(nativeRequestJson(nativeCheckpointRequest(dir, 'result.json', p)));
    const path = join(dir, 'checkpoint-input-' + d + '.json'); writeFileSync(path, JSON.stringify(p));
    assert.throws(() => persistNativeCheckpoint(dir, path, d), /state/);
  }
  for (const name of ['CLAUDE.md', 'claude.local.md', 'nested/AGENTS.md', '.claude/rules/x.md', '.opencode/x', 'CLAUDE.md:stream', 'CLAUDE.md.']) assert.equal(instructionBearingPath(name), true);
  for (const name of ['../progress.json', 'a/CLAUDE.md', 'CLAUDE.md', 'progress.json:stream']) assert.throws(() => exactArtifactPath(dir, name));
  const command = 'node approved-command';
  const policy = { version: 1, artifactRoots: [dir], mechanical: true, allowedCommands: [command], allowedReads: [input], allowedWrites: [{ path: input, digest: nativeRequestSha256(JSON.stringify(payload)) }] };
  const event = (tool_name, tool_input) => ({ tool_name, tool_input, cwd: dir });
  const denied = (tool, args) => assert.equal(artifactToolDecision(event(tool, args), policy).hookSpecificOutput.permissionDecision, 'deny');
  assert.deepEqual(artifactToolDecision(event('Write', { file_path: input, content: JSON.stringify(payload) }), policy), {});
  denied('Write', { file_path: join(dir, 'CLAUDE.md'), content: 'bad' });
  denied('Write', { file_path: join(root, 'CLAUDE.md'), content: 'bad' });
  denied('Write', { file_path: input, content: '{}' });
  denied('Edit', { file_path: input });
  denied('Bash', { command: command + '; echo bad > CLAUDE.md' });
  denied('PowerShell', { command: 'Set-Content CLAUDE.md bad' });
  denied('mcp__files__write', { path: input });
  assert.deepEqual(artifactToolDecision(event('Bash', { command }), policy), {});
  const hookPolicy = join(root, 'policy.json'); writeFileSync(hookPolicy, JSON.stringify(policy));
  const hook = spawnSync(process.execPath, [fileURLToPath(new URL('../artifact-guard.mjs', import.meta.url)), '--hook', hookPolicy], { input: JSON.stringify(event('Write', { file_path: join(dir, 'CLAUDE.md'), content: 'bad' })), encoding: 'utf8' });
  assert.equal(hook.status, 0, hook.stderr); assert.equal(JSON.parse(hook.stdout).hookSpecificOutput.permissionDecision, 'deny');
  const nested = join(dir, 'nested'); mkdirSync(nested); writeFileSync(join(nested, 'CLAUDE.md'), 'owner file retained');
  assert.throws(() => assertArtifactTree(dir), /instruction-bearing/);
  assert.throws(() => persistNativeCheckpoint(dir, input, digest), /instruction-bearing/);
  assert.equal(readFileSync(join(nested, 'CLAUDE.md'), 'utf8'), 'owner file retained');
  rmSync(nested, { recursive: true });
  const linked = join(dir, 'alias'); symlinkSync(root, linked, process.platform === 'win32' ? 'junction' : 'dir');
  assert.throws(() => assertArtifactTree(dir), /unsafe/); rmSync(linked);
  const metadata = { acceptance: '{accept}', policies: {}, profile: '', reviewerContract: { briefs: { role: '{nested {brief}}' } }, inputs: {}, engineMount: null };
  const ref = stageNativeContext(dir, metadata), stagedTime = statSync(ref.path).mtimeMs;
  assert.deepEqual(stageNativeContext(dir, metadata), ref); assert.equal(statSync(ref.path).mtimeMs, stagedTime);
  assert.deepEqual(hydrateNativeContext(dir, { relayContext: ref, context: { dynamic: true } }), { ...metadata, context: { dynamic: true } });
  assert.throws(() => hydrateNativeContext(dir, { relayContext: ref, acceptance: 'override' }), /invalid/);
  writeFileSync(ref.path, '{}'); assert.throws(() => hydrateNativeContext(dir, { relayContext: ref }), /digest/);
  const source = readFileSync(new URL('../factory.js', import.meta.url), 'utf8');
  const helpers = readFileSync(new URL('./native-checkpoint.mjs', import.meta.url), 'utf8');
  for (const name of ['nativeCheckpointRelay', 'nativeCheckpointRequest']) {
    const start = helpers.indexOf('export function ' + name), end = helpers.indexOf('\n}', start) + 2;
    assert.ok(source.includes(helpers.slice(start, end).replace(/^export /, '')));
  }
  assert.ok(nativeCheckpointRelay('/factory', dir, 'progress.json', payload).includes(digest));
  const prepareCli = fileURLToPath(new URL('../prepare-verification.mjs', import.meta.url));
  const contractInput = join(dir, 'verification-contract-input.json'); writeFileSync(contractInput, '{}');
  const rejectedPrepare = spawnSync(process.execPath, [prepareCli, dir, 'run-claim', 'initial', contractInput, '--expected-request', 'a'.repeat(64)], { encoding: 'utf8' });
  assert.equal(rejectedPrepare.status, 1); assert.match(rejectedPrepare.stderr, /digest mismatch/);
  assert.throws(() => statSync(join(dir, 'verify-initial-run-claim.txt')), /ENOENT/);
  const prepared = spawnSync(process.execPath, [prepareCli, dir, 'run-claim', 'initial'], { encoding: 'utf8' });
  assert.equal(prepared.status, 0, prepared.stderr);
  assert.equal(readFileSync(join(dir, 'verify-initial-run-claim.txt'), 'utf8'), '');
  const transcript = 'FACTORY::BUILD::START X.sln\nFACTORY::SUMMARY::build exit=0 errors=0\nFACTORY::TEST::SUITE::START X.sln\nFACTORY::SUMMARY::suite exit=0 failed=0 passed=2 skipped=0\n';
  const expected = { build: ['X.sln'], filter: [], suite: ['X.sln'] };
  const proof = { version: 1, itemId: 'item', runId: 'run', claimId: 'claim', passId: 'pass', band: 'FULL', expected, transcriptHash: createHash('sha256').update(transcript).digest('hex') };
  for (const key of ['codeHash', 'commandHash', 'environmentHash', 'sdkHash']) proof[key] = 'a'.repeat(64);
  const decision = { enabled: true, previous: proof, current: proof, transcript, expected, worktree: resolve(root) };
  assert.equal(nativeIntegrationReuseDecision(decision).reuse, true);
  for (const key of ['codeHash', 'commandHash', 'environmentHash', 'sdkHash', 'claimId', 'runId']) assert.equal(nativeIntegrationReuseDecision({ ...decision, current: { ...proof, [key]: null } }).reuse, false);
  assert.equal(nativeIntegrationReuseDecision({ ...decision, enabled: false }).reuse, false);
  assert.equal(nativeIntegrationReuseDecision({ ...decision, transcript: transcript + 'changed' }).reuse, false);
  assert.equal(nativeIntegrationReuseDecision({ ...decision, expected: { ...expected, suite: ['X.sln', 'Y.sln'] } }).reuse, false);
  console.log('native-artifact: persistence, hooks, context and fail-closed reuse passed');
} finally { rmSync(root, { recursive: true, force: true }); }
